before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
archives:
- name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  files:
  - none*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next+commit.{{ .ShortCommit }}"
release:
  draft: true
brews:
  - github:
      owner: redskyops
      name: homebrew-tap
    commit_author:
      name: Butch Masters
      email: butch@carbonrelay.com
    folder: Formula
    homepage: "https://github.com/carbonrelay/konjure/"
    description: Manifest appear!
