name: Main workflow
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.12.5'
      - name: Check out code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 go build -o konjure-linux-amd64 .
          GOOS=darwin GOARCH=amd64 go build -o konjure-darwin-amd64 .
          sha256sum konjure-* | tee checksums.txt
      - name: Upload linux-amd64
        uses: actions/upload-artifact@master
        with:
          name: konjure-linux-amd64
          path: konjure-linux-amd64
      - name: Upload darwin-amd64
        uses: actions/upload-artifact@master
        with:
          name: konjure-darwin-amd64
          path: konjure-darwin-amd64
      - name: Upload checksums
        uses: actions/upload-artifact@master
        with:
          name: checksums.txt
          path: checksums.txt
