name: Master
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.14
      - name: Test
        run: |
          go mod tidy
          go vet ./...
          go test ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.BMASTERS_TOKEN }}
      - name: Clean up dist
        run: 'rm dist/config.yaml dist/*.tar.gz'
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
